### YamlMime:ManagedReference
items:
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  commentId: T:Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  id: EntityExtensions
  parent: Biwen.QuickApi.Application.EntityEvents
  children:
  - Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync``1(``0)
  - Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync``1(``0)
  - Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync``1(``0)
  langs:
  - csharp
  - vb
  name: EntityExtensions
  nameWithType: EntityExtensions
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  type: Class
  source:
    href: https://github.com/vipwan/Biwen.QuickApi/blob/67900c6dd4da4c9a7da43916a4a35c1977aa0c94/Biwen.QuickApi/Application/EntityEvents/IEntityEvent.cs
  assemblies:
  - Biwen.QuickApi
  namespace: Biwen.QuickApi.Application.EntityEvents
  syntax:
    content: >-
      [SuppressType]

      public static class EntityExtensions
    content.vb: >-
      <SuppressType>

      Public Module EntityExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  attributes:
  - type: Biwen.QuickApi.Infrastructure.SuppressTypeAttribute
    ctor: Biwen.QuickApi.Infrastructure.SuppressTypeAttribute.#ctor
    arguments: []
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync``1(``0)
  commentId: M:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync``1(``0)
  id: PublishAddedAsync``1(``0)
  isExtensionMethod: true
  parent: Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  langs:
  - csharp
  - vb
  name: PublishAddedAsync<T>(T)
  nameWithType: EntityExtensions.PublishAddedAsync<T>(T)
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync<T>(T)
  type: Method
  source:
    href: https://github.com/vipwan/Biwen.QuickApi/blob/67900c6dd4da4c9a7da43916a4a35c1977aa0c94/Biwen.QuickApi/Application/EntityEvents/IEntityEvent.cs
  assemblies:
  - Biwen.QuickApi
  namespace: Biwen.QuickApi.Application.EntityEvents
  summary: 通知实体 <code class="typeparamref">T</code> 添加事件
  example: []
  syntax:
    content: 'public static Task PublishAddedAsync<T>(this T entity) where T : class'
    parameters:
    - id: entity
      type: '{T}'
      description: ''
    typeParameters:
    - id: T
      description: ''
    return:
      type: System.Threading.Tasks.Task
      description: ''
    content.vb: Public Shared Function PublishAddedAsync(Of T As Class)(entity As T) As Task
  overload: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync*
  nameWithType.vb: EntityExtensions.PublishAddedAsync(Of T)(T)
  fullName.vb: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync(Of T)(T)
  name.vb: PublishAddedAsync(Of T)(T)
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync``1(``0)
  commentId: M:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync``1(``0)
  id: PublishUpdatedAsync``1(``0)
  isExtensionMethod: true
  parent: Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  langs:
  - csharp
  - vb
  name: PublishUpdatedAsync<T>(T)
  nameWithType: EntityExtensions.PublishUpdatedAsync<T>(T)
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync<T>(T)
  type: Method
  source:
    href: https://github.com/vipwan/Biwen.QuickApi/blob/67900c6dd4da4c9a7da43916a4a35c1977aa0c94/Biwen.QuickApi/Application/EntityEvents/IEntityEvent.cs
  assemblies:
  - Biwen.QuickApi
  namespace: Biwen.QuickApi.Application.EntityEvents
  summary: 通知实体 <code class="typeparamref">T</code> 更新事件
  example: []
  syntax:
    content: 'public static Task PublishUpdatedAsync<T>(this T entity) where T : class'
    parameters:
    - id: entity
      type: '{T}'
      description: ''
    typeParameters:
    - id: T
      description: ''
    return:
      type: System.Threading.Tasks.Task
      description: ''
    content.vb: Public Shared Function PublishUpdatedAsync(Of T As Class)(entity As T) As Task
  overload: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync*
  nameWithType.vb: EntityExtensions.PublishUpdatedAsync(Of T)(T)
  fullName.vb: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync(Of T)(T)
  name.vb: PublishUpdatedAsync(Of T)(T)
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync``1(``0)
  commentId: M:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync``1(``0)
  id: PublishDeletedAsync``1(``0)
  isExtensionMethod: true
  parent: Biwen.QuickApi.Application.EntityEvents.EntityExtensions
  langs:
  - csharp
  - vb
  name: PublishDeletedAsync<T>(T)
  nameWithType: EntityExtensions.PublishDeletedAsync<T>(T)
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync<T>(T)
  type: Method
  source:
    href: https://github.com/vipwan/Biwen.QuickApi/blob/67900c6dd4da4c9a7da43916a4a35c1977aa0c94/Biwen.QuickApi/Application/EntityEvents/IEntityEvent.cs
  assemblies:
  - Biwen.QuickApi
  namespace: Biwen.QuickApi.Application.EntityEvents
  summary: 通知实体 <code class="typeparamref">T</code> 删除事件
  example: []
  syntax:
    content: 'public static Task PublishDeletedAsync<T>(this T entity) where T : class'
    parameters:
    - id: entity
      type: '{T}'
      description: ''
    typeParameters:
    - id: T
      description: ''
    return:
      type: System.Threading.Tasks.Task
      description: ''
    content.vb: Public Shared Function PublishDeletedAsync(Of T As Class)(entity As T) As Task
  overload: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync*
  nameWithType.vb: EntityExtensions.PublishDeletedAsync(Of T)(T)
  fullName.vb: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync(Of T)(T)
  name.vb: PublishDeletedAsync(Of T)(T)
references:
- uid: Biwen.QuickApi.Application.EntityEvents
  commentId: N:Biwen.QuickApi.Application.EntityEvents
  isExternal: true
  href: Biwen.html
  name: Biwen.QuickApi.Application.EntityEvents
  nameWithType: Biwen.QuickApi.Application.EntityEvents
  fullName: Biwen.QuickApi.Application.EntityEvents
  spec.csharp:
  - uid: Biwen
    name: Biwen
    isExternal: true
    href: Biwen.html
  - name: .
  - uid: Biwen.QuickApi
    name: QuickApi
    isExternal: true
    href: Biwen.QuickApi.html
  - name: .
  - uid: Biwen.QuickApi.Application
    name: Application
    isExternal: true
    href: Biwen.QuickApi.Application.html
  - name: .
  - uid: Biwen.QuickApi.Application.EntityEvents
    name: EntityEvents
    isExternal: true
    href: Biwen.QuickApi.Application.EntityEvents.html
  spec.vb:
  - uid: Biwen
    name: Biwen
    isExternal: true
    href: Biwen.html
  - name: .
  - uid: Biwen.QuickApi
    name: QuickApi
    isExternal: true
    href: Biwen.QuickApi.html
  - name: .
  - uid: Biwen.QuickApi.Application
    name: Application
    isExternal: true
    href: Biwen.QuickApi.Application.html
  - name: .
  - uid: Biwen.QuickApi.Application.EntityEvents
    name: EntityEvents
    isExternal: true
    href: Biwen.QuickApi.Application.EntityEvents.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync*
  commentId: Overload:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync
  isExternal: true
  href: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.html#Biwen_QuickApi_Application_EntityEvents_EntityExtensions_PublishAddedAsync__1___0_
  name: PublishAddedAsync
  nameWithType: EntityExtensions.PublishAddedAsync
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishAddedAsync
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync*
  commentId: Overload:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync
  isExternal: true
  href: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.html#Biwen_QuickApi_Application_EntityEvents_EntityExtensions_PublishUpdatedAsync__1___0_
  name: PublishUpdatedAsync
  nameWithType: EntityExtensions.PublishUpdatedAsync
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishUpdatedAsync
- uid: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync*
  commentId: Overload:Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync
  isExternal: true
  href: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.html#Biwen_QuickApi_Application_EntityEvents_EntityExtensions_PublishDeletedAsync__1___0_
  name: PublishDeletedAsync
  nameWithType: EntityExtensions.PublishDeletedAsync
  fullName: Biwen.QuickApi.Application.EntityEvents.EntityExtensions.PublishDeletedAsync
